### ISSUE TITLE
Replace normalize-url

### ISSUE THREAD

**Issue by mistic** [IonicaBizau/parse-url#15]
@IonicaBizau do you think we can replace `normalize-url` with some other package (or at least forking it and use a transpilled ES5 version of it into this package)? `normalize-url` is shipping ES6 code which will cause problems when using this package in the browser and I don't also also think that transpile node_modules on our side when using that library would be a solution too. What do u think?

**Comment by IonicaBizau** [comment]
You will have to transpile the entire bundle anyways...

**Comment by mistic** [comment]
@IonicaBizau can't we just fork https://github.com/sindresorhus/normalize-url , bundling it and distribute it as ES5 code and then use it as a dependency of `parse-url` instead of the original one? I can put up a PR for it if you want

**Comment by IonicaBizau** [comment]
No, sorry. You have to set up your build steps to transpile the bundle into ES5 if you want to have older browser support.

**Comment by mistic** [comment]
In my own opinion we should rely on node_modules as they are distributed and not transpile them, specially in larger codebases. Thanks for the feedback anyway.
