### ISSUE TITLE
parse-url at version 6 doesn't work on Safari

### ISSUE THREAD

**Issue by edenhermelin** [IonicaBizau/parse-url#31]
Hi,
since version 6 of the module it seems as it doesn't work anymore on safari. 
probably because it used a positive lookahead regex which is not supported on Safari.
@IonicaBizau can we please adjust the regex in a way that will work on Safari?   

the regex: 
```
/(?<!\b(?:[a-z][a-z\d+\-.]{1,50}:))\/{2,}/g
```

relevant other issue - https://github.com/IonicaBizau/parse-url/issues/22

Thanks!

**Comment by IonicaBizau** [comment]
Hi @edenhermelin! I am not sure how this should be solved... Ideally, `normalize-url` should get a patch...

**Comment by edenhermelin** [comment]
hey @IonicaBizau, thanks for the quick response!
for some reason I thought the regex is defined in `parse-url`. 
I commented on an already-opened issue there: https://github.com/sindresorhus/normalize-url/issues/142 (welcome to upvote if you want 😃 )

Thanks anyway!

**Comment by freben** [comment]
@IonicaBizau Sorry for commenting on the closed issue, but the README of `normalize-url` _explicitly states_ that if you want your code to work in a browser environment, you should stay on the 4.x line of `normalize-url`.

I think that [this commit](https://github.com/IonicaBizau/parse-url/commit/e8dbac15371a798bcf2eeff3dcfa6e13f97e7abe) that upgraded `normalize-url` should be backtracked and made sure to stay on 4.x after that. Unless, of course, you explicitly want some newer features of that library, but if you do, you are also unfortunately also going to have to live with `parse-url` and `git-url-parse` being incompatible with widely used browsers.

Maybe a prudent choice could even be to internalize the necessary parts of `normalize-url` into your library, and dropping that dependency entirely.

**Comment by IonicaBizau** [comment]
> Maybe a prudent choice could even be to internalize the necessary parts of normalize-url into your library, and dropping that dependency entirely.

@freben I thought of that too, but would like to keep it modular... 

> but the README of normalize-url explicitly states that if you want your code to work in a browser environment, you should stay on the 4.x line of normalize-url.

Can you please send me a link a of that? I couldn't find it...

**Comment by freben** [comment]
> Can you please send me a link a of that? I couldn't find it...

Sure! It's near the top of [the readme](https://github.com/sindresorhus/normalize-url#install). Seems to be an intentional choice he made.

He does not seem to respond to [the issue](https://github.com/sindresorhus/normalize-url/issues/142) about this problem either.

**Comment by freben** [comment]
Also made an attempt at contributing a fix: https://github.com/sindresorhus/normalize-url/pull/148

**Comment by edenhermelin** [comment]
hey @IonicaBizau ,
just wanted to bump this issue in case you are working on a fix. 
as @freben mentioned here, the `normalize-url` library released version 7 that includes a fix - but it looks like it cannot be used in the project..

**Comment by IonicaBizau** [comment]
@edenhermelin Sorry for the late reply. I'm getting the following error when upgrading to the latest version:

```sh
.../parse-url/lib/index.js:4
    , normalizeUrl = require("normalize-url")
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module .../parse-url/node_modules/normalize-url/index.js from .../parse-url/lib/index.js not supported.
Instead change the require of .../parse-url/node_modules/normalize-url/index.js in .../parse-url/lib/index.js to a dynamic import() which is available in all CommonJS modules.
  ...
  code: 'ERR_REQUIRE_ESM'
}
```

I am wondering if there is any simple way to fix this. Is `import` supported natively in Node.js?

**Comment by edenhermelin** [comment]
hey, @IonicaBizau thanks for getting back to me!

I know that there are ways to convert the project to use ESM/ to dynamically import ESM dependencies like mentioned in [this gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) by 
sindresorhus (normalize-url's maintainer).

I don't know if these are approaches that you want to do in your project though.

I did clone the repo and tried to just take the `index.js` from `normalize-url` and call it from your code, and it seems to work just fine 🤔 
I'm wondering if there shouldn't be a way to just minify/transpile `normalize-url` after it's being installed to just be a commonJS file. I'll try to search more online, but perhaps you can ask 
also the community of https://github.com/sindresorhus/normalize-url ?

**Comment by edenhermelin** [comment]
Hey @IonicaBizau , I pushed a PR that should fix the issue.
Please let me know what do you think :)
locally it seems as it works with the provided example
