### ISSUE TITLE
7.0.0+ unexpected breaking change: `git://` URLs are no longer supported

### ISSUE THREAD

**Issue by nbouvrette** [IonicaBizau/parse-url#46]
This issue is related to these two issues:

- https://github.com/release-it/release-it/issues/917
- https://github.com/IonicaBizau/git-url-parse/issues/140

I am not sure if the issue has been caused by this repo or by https://github.com/IonicaBizau/parse-path

If this is by this repo, I suspect this new regular expression might be the cause: 

https://github.com/IonicaBizau/parse-url/blob/21c72ab9412228eea753e2abc48f8962707b1fe3/lib/index.js#L40

But in a nutshell, before you did many changes to many of your repositories, this URL: `git://github.com:user/repo` resolved to this:

```js
{
  protocols: [ 'git' ],
  protocol: 'ssh',
  port: null,
  resource: 'github.com',
  user: '',
  pathname: '/user/repo',
  hash: '',
  search: '',
  href: 'git://github.com:user/repo',
  query: [Object: null prototype] {},
  token: '',
  toString: [Function (anonymous)],
  source: 'github.com',
  git_suffix: false,
  name: 'repo',
  owner: 'user',
  commit: undefined,
  ref: '',
  filepathtype: '',
  filepath: '',
  organization: 'user',
  full_name: 'user/repo'
}
```

After your changes it now resolves to this:

```js
{
  protocols: [ 'file' ],
  protocol: 'file',
  port: '',
  resource: '',
  user: '',
  password: '',
  pathname: '',
  hash: '',
  search: '',
  href: 'git://github.com:user/repo',
  query: {},
  token: '',
  toString: [Function (anonymous)],
  source: '',
  git_suffix: false,
  name: 'repo',
  owner: 'git://github.com:user',
  commit: undefined,
  ref: '',
  filepathtype: '',
  filepath: '',
  organization: 'git://github.com:user',
  full_name: 'git://github.com:user/repo'
}
```

**Comment by IonicaBizau** [comment]
@nbouvrette I am checking this now. I guess it should be `git://github.com/user/repo` (`/` instead of `:`).

Consider that `github.com` accepts usernames made of numbers, so this happens:

```sh
$ git clone -v git://github.com:42/42-bootstrap.git
Cloning into '42-bootstrap'...
warning: templates not found in /home/ionicabizau/.git-templates
Looking up github.com ... done.
Connecting to github.com (port 42) ... ^C
```

Should I may miss anything, do let me know. 😁

**Comment by mhassan1** [comment]
@IonicaBizau I just wanted to confirm: is this a breaking change that won't be restored? I couldn't tell from your response.

**Comment by IonicaBizau** [comment]
@mhassan1 Like commented above, I don't see any case where we would use `git://domain.com:path/name`. Does `git` itself support such URLs?

**Comment by mhassan1** [comment]
Makes sense. It seems like `git` doesn't support it. I think I was just misunderstanding your concluding comment. Thank you.
