### ISSUE TITLE
Wrong results with folders starting with numbers

### ISSUE THREAD

**Issue by oscarotero** [IonicaBizau/parse-url#5]
Hi. Thanks for this great library!
I found an issue related with folders starting with numbers in ssh urls. Seems like parse-url gets the number as the port and remove the rest of the dirname. Example:

```js
const result = parseUrl('user@host.com:1234group/Project.git');

console.log(result);

/*
{ protocols: [],
  protocol: 'ssh',
  port: 1234,
  resource: 'host.com',
  user: 'user',
  pathname: '/Project.git',
  hash: '',
  search: '',
  href: 'user@host.com:1234group/Project.git' }
*/
```
As you can see, `pathname` should be `1234group/Project.git`, and the port should be undefined, but `parse-url` use 1234 as port number and ignores the rest of that folder name.

**Comment by oscarotero** [comment]
Ok, I just realized this bug is filed here: https://github.com/IonicaBizau/parse-path/issues/5
I close this.

**Comment by IonicaBizau** [comment]
Should be fixed via https://github.com/IonicaBizau/parse-path/pull/23.
