### ISSUE TITLE
TypeScript support missing in 8.0

### ISSUE THREAD

**Issue by ffflorian** [IonicaBizau/parse-url#64]
Hi,

in version 8.0.0 the `index.d.ts` file was removed, thus removing the support for TypeScript. Any plans to bring it back? Or should we use [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by IonicaBizau** [comment]
This should be fixed in 8.1.0. Please let me know if there are still issues with this. ❇️

**Comment by ffflorian** [comment]
Perfect, thanks!
