### ISSUE TITLE
Are there any plans to provide parsed URL serialization?

### ISSUE THREAD

**Issue by edenworky** [IonicaBizau/parse-url#70]
Would there be a way to get a URL representation of a mutated parsed URL? I'm not sure what the best API for this would be, but just as an illustration:

```javascript
let parsed = parseUrl('http://example.com')
parsed.query.foo = 1
expect(parsed.toString()).toEqual('http://example.com?foo=1')
```

Or is this out of scope for this package?

**Comment by IonicaBizau** [comment]
Sorry for the late reply on this! 

Yes, I suggest this should be done in a different package eventually. `parse-url` is primarily for parsing. The other package might handle something like this, taking the object from `parse-url` and stringifying it.
