### ISSUE TITLE
NPM version is not the latest

### ISSUE THREAD

**Issue by YanxinTang** [IonicaBizau/parse-url#71]
The version of this module on npm is v8.1.0, which has a type error that there is no `password` property of `ParsedUrl`

https://www.npmjs.com/package/parse-url

**Comment by marcgeeklaberge** [comment]
I'm having same problem, 
`npm i parse-url@latest --save`
will update to maximum 8.1.0
and `npm i parse-url@8.1.1--save`
is failing.

**Comment by revolunet** [comment]
@IonicaBizau Hi, any chance we get an updated release please ?

**Comment by IonicaBizau** [comment]
Should be fixed now :)
